# Generated by Django 3.0.5 on 2021-01-21 15:59

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authname',
            field=models.CharField(default='AuthName', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='dp',
            field=models.ImageField(default='0', upload_to='bookDP/'),
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publist',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, default='2021-01-21T14:55:16.320781Z'),
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='share',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
