# Generated by Django 3.1.5 on 2021-01-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0003_remove_book_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booktype',
            field=models.CharField(default='Text', max_length=200),
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.book')),
            ],
        ),
    ]
