# Generated by Django 3.1.5 on 2021-01-21 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialBookApp', '0004_auto_20210122_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='app_user',
            name='country',
            field=models.CharField(default='Canada', max_length=200),
        ),
        migrations.AddField(
            model_name='app_user',
            name='friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app_user',
            name='mailid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='app_user',
            name='username',
            field=models.CharField(default='both', max_length=200),
        ),
        migrations.AddField(
            model_name='app_user',
            name='usertype',
            field=models.CharField(default='both', max_length=200),
        ),
        migrations.AddField(
            model_name='app_user',
            name='wallet',
            field=models.IntegerField(default=500),
        ),
        migrations.CreateModel(
            name='profileComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentfriend', to=settings.AUTH_USER_MODEL)),
                ('you', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentyou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Own', models.CharField(default='no', max_length=200)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='friendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default='addfriend', max_length=200)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistfriend', to=settings.AUTH_USER_MODEL)),
                ('you', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistyou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
