# Generated by Django 3.1.5 on 2021-01-21 20:27

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0005_auto_20210122_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publist',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True),
        ),
    ]
