# Generated by Django 3.1.5 on 2021-01-21 20:44

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0006_auto_20210122_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='user',
        ),
        migrations.AddField(
            model_name='app_user',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(default='*', max_length=600),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistfriend', to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='you',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistyou', to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='ownbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='profilecomment',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentfriend', to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='profilecomment',
            name='you',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentyou', to='SocialBookApp.app_user'),
        ),
    ]
