# Generated by Django 3.1.5 on 2021-01-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0008_auto_20210122_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownbook',
            name='Book',
        ),
        migrations.RemoveField(
            model_name='ownbook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookComments',
        ),
        migrations.DeleteModel(
            name='OwnBook',
        ),
        migrations.DeleteModel(
            name='TextBook',
        ),
    ]
