# Generated by Django 3.1.5 on 2021-01-21 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0011_auto_20210122_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentfriend', to='SocialBookApp.app_user')),
                ('you', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileCommentyou', to='SocialBookApp.app_user')),
            ],
        ),
        migrations.CreateModel(
            name='friendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default='addfriend', max_length=200)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistfriend', to='SocialBookApp.app_user')),
                ('you', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlistyou', to='SocialBookApp.app_user')),
            ],
        ),
    ]
