# Generated by Django 3.1.5 on 2021-01-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0012_friendlist_profilecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
        ),
        migrations.AlterField(
            model_name='bookcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
        ),
    ]
