# Generated by Django 3.1.5 on 2021-02-15 18:28

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0013_auto_20210122_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='usertype',
            field=models.CharField(max_length=200),
        ),
    ]
