# Generated by Django 3.1.5 on 2021-02-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0015_auto_20210216_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_user',
            old_name='username',
            new_name='user',
        ),
    ]
