# Generated by Django 3.1.5 on 2021-02-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0016_auto_20210216_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='username',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
