# Generated by Django 3.1.5 on 2021-02-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0018_auto_20210216_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_user',
            old_name='mailid',
            new_name='email',
        ),
    ]
