# Generated by Django 3.1.5 on 2021-02-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0019_auto_20210216_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='email',
        ),
    ]
