# Generated by Django 3.1.5 on 2021-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0020_remove_app_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
