# Generated by Django 3.1.5 on 2021-02-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0021_app_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
