# Generated by Django 3.1.5 on 2021-02-16 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialBookApp', '0023_auto_20210216_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='App_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
