# Generated by Django 3.1.5 on 2021-02-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0024_auto_20210217_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='likes',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='friendlist',
            old_name='you',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profilecomment',
            old_name='you',
            new_name='user',
        ),
        migrations.CreateModel(
            name='TXTPostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user')),
            ],
        ),
        migrations.CreateModel(
            name='profileTXTPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('comments', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user')),
            ],
        ),
    ]
