# Generated by Django 3.1.5 on 2021-03-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0025_auto_20210325_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txtpostcomments',
            name='dp',
        ),
        migrations.RemoveField(
            model_name='txtpostcomments',
            name='header',
        ),
        migrations.RemoveField(
            model_name='txtpostcomments',
            name='related',
        ),
        migrations.RemoveField(
            model_name='txtpostcomments',
            name='share',
        ),
        migrations.RemoveField(
            model_name='txtpostcomments',
            name='types',
        ),
        migrations.RemoveField(
            model_name='txtpostcomments',
            name='url',
        ),
        migrations.AddField(
            model_name='profiletxtpost',
            name='dp',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiletxtpost',
            name='header',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiletxtpost',
            name='related',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiletxtpost',
            name='types',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiletxtpost',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='txtpostcomments',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='txtpostcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.profiletxtpost'),
        ),
    ]
