# Generated by Django 3.1.5 on 2021-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0026_auto_20210325_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletxtpost',
            name='dp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
