# Generated by Django 3.1.5 on 2021-02-17 10:14

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0026_auto_20210217_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletxtpost',
            name='publist',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True),
        ),
    ]
