# Generated by Django 3.1.5 on 2021-02-17 10:15

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0027_profiletxtpost_publist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecomment',
            name='publist',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True),
        ),
    ]
