# Generated by Django 3.1.5 on 2021-02-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0028_profilecomment_publist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletxtpost',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
