# Generated by Django 3.1.5 on 2021-02-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0029_auto_20210217_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txtpostcomments',
            name='post',
        ),
        migrations.DeleteModel(
            name='profileTXTPost',
        ),
        migrations.DeleteModel(
            name='TXTPostComments',
        ),
    ]
