# Generated by Django 3.1.5 on 2021-02-17 11:43

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0030_auto_20210217_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='TXTPostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user')),
            ],
        ),
        migrations.CreateModel(
            name='profileTXTPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('comments', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user')),
            ],
        ),
    ]
