# Generated by Django 3.1.5 on 2021-02-19 22:42

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0031_profiletxtpost_txtpostcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='dp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='dp',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookcomments',
            name='publist',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ownbook',
            name='publist',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='profilecomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textbook',
            name='publist',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='txtpostcomments',
            name='publist',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='txtpostcomments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='txtpostcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.profiletxtpost'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialBookApp.app_user')),
            ],
        ),
    ]
