# Generated by Django 3.1.5 on 2021-02-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0034_textbook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
