# Generated by Django 3.1.5 on 2021-02-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBookApp', '0035_auto_20210220_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownbook',
            name='Own',
            field=models.CharField(max_length=200),
        ),
    ]
